ENH: add coord.interp_to_cube_time()

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -12,23 +12,26 @@ jobs:
 
     steps:
     - uses: actions/checkout@v2
-    - uses: ammaraskar/sphinx-action@master
-      with:
-        build-command: "sphinx-build -n -b html -d docs/_build/doctrees docs/source docs/_build/html"
-        docs-folder: "docs/"
-    - name: Commit documentation changes
+    - name: Build docs
       run: |
-        git clone https://github.com/${{ secrets.repository }}.git --branch gh-pages --single-branch gh-pages
-        cp -r docs/_build/html/* gh-pages/
-        cd gh-pages
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore that.
-    - name: Push changes
-      uses: ad-m/github-push-action@master
-      with:
-        branch: gh-pages
-        directory: gh-pages
-        github_token: ${{ secrets.GITHUB_TOKEN }}
+        echo "To be implemented..."
+#    - uses: ammaraskar/sphinx-action@master
+#      with:
+#        build-command: "sphinx-build -n -b html -d docs/_build/doctrees docs/source docs/_build/html"
+#        docs-folder: "docs/"
+#    - name: Commit documentation changes
+#      run: |
+#        git clone https://github.com/${{ secrets.repository }}.git --branch gh-pages --single-branch gh-pages
+#        cp -r docs/_build/html/* gh-pages/
+#        cd gh-pages
+#        git config --local user.email "action@github.com"
+#        git config --local user.name "GitHub Action"
+#        git add .
+#        git commit -m "Update documentation" -a || true
+#        # The above command will fail if no changes were present, so we ignore that.
+#    - name: Push changes
+#      uses: ad-m/github-push-action@master
+#      with:
+#        branch: gh-pages
+#        directory: gh-pages
+#        github_token: ${{ secrets.GITHUB_TOKEN }}
